# Atividade 01 - Etapa 01 
Desenvolvedor: Sérgio Strack Junior

Dados Numéricos 
 
Operações básicas para entendimento do python


In [52]:
# Variável inteira
#print é utilizado para mostrar algo
a = 5
print('Valor de a = '+str(a))
type(a)

Valor de a = 5


int

In [53]:
# Variável dupla precisão
b = 5.0
print(b)
type(b)

5.0


float

In [54]:
# Converter float para int
# mudando as váriaveis 
c = int(b)
print(c)
type(c)

5


int

In [55]:
# Delacrando nan (operações matemáticas)
import numpy as np
d = np.nan
print(d)
type(d)

nan


float

In [56]:
# Operação com NaN
e = d*5
print(e)
e = d+5
print(e)
e = np.nansum([d,5])
print(e)

nan
nan
5.0


## Dados de texto

In [57]:
# Declaração de variável texto
f = 'Sérgio'
g = "Strack"
print(f)
print(g)
print(f+g)
print(f+' '+g)

Sérgio
Strack
SérgioStrack
Sérgio Strack


## Dados tipo bool - lógica

In [58]:
# == é pra verificar a = b 
a == 5

True

In [59]:
h = (a==5)
print(h)
type(h)

True


bool

In [60]:
h = (a==5)
print(h)
type(h)

True


bool

In [61]:
i = True
type(i)

bool

In [62]:
# Retorna o tipo de dados da variáve
ii = 'True'
type(ii)

str

## Operação de Coparação

In [63]:
# Soma 
2+3

5

In [64]:
# Soma e atribui valor
ab = 7+9
print(ab)

16


In [65]:
# Multiplicação
l = a*b # Não use l como variável
print("Não use l como nome de variável")
j = 3*5
print(j)

Não use l como nome de variável
15


In [66]:
# Divisão
6/2

3.0

In [67]:
# Potencia
5**2

25

In [68]:
# Operações matemáticas com a bibliotéca math 
import math

math.exp(100)

2.6881171418161356e+43

In [69]:
math.exp(9)

8103.083927575384

In [70]:
math.exp(8)

2980.9579870417283

In [71]:
math.exp(-1)

0.36787944117144233

In [72]:
#puxando a biblioteca (mt - usado para chamar a função math reduzido para mt)
import math as mt
mt.log(73)

4.290459441148391

In [73]:
mt.log10(5)

0.6989700043360189

## Listas

In [74]:
#manipulação de lista
myFirstList = [5,10,15]
print(myFirstList)

[5, 10, 15]


In [75]:
myFirstList==5

False

In [76]:
myFirstList[1]==a

False

In [77]:
mySecList = [5,a,'c']
print(mySecList)

[5, 5, 'c']


In [78]:
type(mySecList)

list

In [79]:
type(mySecList[2])

str

In [80]:
type(mySecList[1])

int

## Caminhos = Path

In [81]:
#Listar o caminho do diretório

path = r"C:\Users\Win10\Documents\airpolution"
print(path)

C:\Users\Win10\Documents\airpolution


In [82]:
path = "C:/Users/Win10/Documents/airpolution"
print(path)

C:/Users/Win10/Documents/airpolution


In [83]:
import os 
# Listar arquivos na pasta
os.listdir(path)

['.git', '.gitignore', 'dados', 'figuras', 'README.md', 'scripts']

In [84]:
# Selecionar primeiro arquivo listado
os.listdir(path)[3]

'figuras'

In [85]:
# Concatenando caminhos
path+"/"+os.listdir(path)[0]

'C:/Users/Win10/Documents/airpolution/.git'

In [86]:
# Listando caminho concatenado
os.listdir(path+"/"+os.listdir(path)[0])

['COMMIT_EDITMSG',
 'config',
 'description',
 'FETCH_HEAD',
 'HEAD',
 'hooks',
 'index',
 'info',
 'logs',
 'objects',
 'ORIG_HEAD',
 'packed-refs',
 'refs']

In [87]:
# Diretório que estou trababalhando
os.getcwd()

'C:\\Users\\Win10\\Documents'

In [88]:
# Mudo de diretório para o caminho 
os.chdir('C:\\Users\\Win10\\Documents\\')

In [89]:
os.getcwd()

'C:\\Users\\Win10\\Documents'

In [90]:
# Criando diretório
new_path = os.getcwd()+'/test'

if os.path.isdir(new_path):
    print('diretório já existe')
else:
    print('Criando diretório '+new_path)
    os.mkdir(new_path)

diretório já existe


In [91]:
# Criando diretório
new_path = os.getcwd()+'/test2'

if os.path.isdir(new_path):
    print('diretório já existe')
    # Criando um arquivo de texto
    with open(new_path+"/copy.txt", "w") as file:
        file.write("Your text goes here")
else:
    print('Criando diretório '+new_path)
    os.mkdir(new_path)
    with open(new_path+"/copy.txt", "w") as file:
        file.write("Your text goes here")

diretório já existe


## Numpy arrays e Pandas DataFrames

In [92]:
import numpy as np
# Criando uma variável numpy
n = np.array(0)
type(n)

numpy.ndarray

In [93]:
# Criando uma variável numpy a partir de uma lista
myThirdList=[5,10,15,20,25,30]
n = np.array(myThirdList)
print(n)

[ 5 10 15 20 25 30]


In [94]:
# Criando uma matriz de 10x10 de números aleatórios entre 0 e 1
n = np.random.rand(5,5)
print(n)
# Dimensões da matrix
print(n.shape)

[[0.74182605 0.70192188 0.30637789 0.69573401 0.34542035]
 [0.14116558 0.16956543 0.96053541 0.06030158 0.72380381]
 [0.70716337 0.86588831 0.18489593 0.87789655 0.85879005]
 [0.72916421 0.59802408 0.45554291 0.94989464 0.20378426]
 [0.51827826 0.879893   0.92209149 0.56988466 0.57138201]]
(5, 5)


In [95]:
# Acessando valores da matriz
n[3,:]

array([0.72916421, 0.59802408, 0.45554291, 0.94989464, 0.20378426])

In [96]:
n[:,3]

array([0.69573401, 0.06030158, 0.87789655, 0.94989464, 0.56988466])

In [97]:
n[:,3:4]

array([[0.69573401],
       [0.06030158],
       [0.87789655],
       [0.94989464],
       [0.56988466]])

In [98]:
n[0,3:4]

array([0.69573401])

In [99]:
n[0,-4]

0.7019218791495095

In [100]:
n[0,3:-1]

array([0.69573401])

In [101]:
n[0,2:]

array([0.30637789, 0.69573401, 0.34542035])

In [102]:
#resultado da matriz de log10
an = np.log(n*10)
print(an)

[[ 2.0039446   1.94865193  1.11964908  1.93979724  1.23959191]
 [ 0.34476334  0.52806869  2.26232066 -0.50581196  1.97935019]
 [ 1.95609153  2.15858574  0.61462291  2.17235858  2.1503543 ]
 [ 1.98672878  1.78846083  1.51631974  2.25118089  0.7118917 ]
 [ 1.6453421   2.17463012  2.22147427  1.7402638   1.74288781]]
