Aula 02 - Python \
Dados Numéricos


In [1]:
# Variável inteira
#print é utilizado para mostrar algo
a = 5
print('Valor de a = '+str(a))
type(a)

Valor de a = 5


int

In [2]:
# Variável dupla precisão
b = 5.0
print(b)
type(b)

5.0


float

In [3]:
# Converter float para int
# mudando as váriaveis 
c = int(b)
print(c)
type(c)

5


int

In [4]:
# Delacrando nan
import numpy as np
d = np.nan
print(d)
type(d)

nan


float

In [5]:
# Operação com NaN
e = d*5
print(e)
e = d+5
print(e)
e = np.nansum([d,5])
print(e)

nan
nan
5.0


## Dados de texto

In [6]:
# Declaração de variável texto
f = 'Sérgio'
g = "Strack"
print(f)
print(g)
print(f+g)
print(f+' '+g)

Sérgio
Strack
SérgioStrack
Sérgio Strack


## Dados tipo bool - lógica

In [7]:
# == é pra verificar a = b 
a == 5

True

In [8]:
h = (a==5)
print(h)
type(h)

True


bool

In [9]:
h = (a==5)
print(h)
type(h)

True


bool

In [10]:
i = True
type(i)

bool

In [11]:
# Retorna o tipo de dados da variáve
ii = 'True'
type(ii)

str

## Operação de Coparação

In [12]:
# Soma 
2+3

5

In [13]:
# Soma e atribui valor
ab = 7+9
print(ab)

16


In [14]:
# Multiplicação
l = a*b # Não use l como variável
print("Não use l como nome de variável")
j = 3*5
print(j)

Não use l como nome de variável
15


In [15]:
# Divisão
6/2

3.0

In [16]:
# Potencia
5**2

25

In [17]:
# Operações matemáticas com a bibliotéca math
import math

math.exp(100)

2.6881171418161356e+43

In [18]:
math.exp(9)

8103.083927575384

In [19]:
math.exp(8)

2980.9579870417283

In [20]:
math.exp(-1)

0.36787944117144233

In [21]:
#puxando a biblioteca
import math as mt
mt.log(73)

4.290459441148391

In [22]:
mt.log10(5)

0.6989700043360189

## Listas

In [23]:
myFirstList = [5,10,15]
print(myFirstList)

[5, 10, 15]


In [24]:
myFirstList==5

False

In [25]:
myFirstList[1]==a

False

In [26]:
mySecList = [5,a,'c']
print(mySecList)

[5, 5, 'c']


In [27]:
type(mySecList)

list

In [28]:
type(mySecList[2])

str

In [29]:
type(mySecList[1])

int

## Caminhos = Path

In [30]:
path = r"C:\Users\Win10\Documents\airpolution"
print(path)

C:\Users\Win10\Documents\airpolution


In [31]:
path = "C:/Users/Win10/Documents/airpolution"
print(path)

C:/Users/Win10/Documents/airpolution


In [32]:
import os 
# Listar arquivos na pasta
os.listdir(path)

['.git', 'dados', 'figuras', 'README.md', 'scripts']

In [33]:
# Selecionar primeiro arquivo listado
os.listdir(path)[3]

'README.md'

In [34]:
# Concatenando caminhos
path+"/"+os.listdir(path)[0]

'C:/Users/Win10/Documents/airpolution/.git'

In [35]:
# Listando caminho concatenado
os.listdir(path+"/"+os.listdir(path)[0])

['COMMIT_EDITMSG',
 'config',
 'description',
 'FETCH_HEAD',
 'HEAD',
 'hooks',
 'index',
 'info',
 'logs',
 'objects',
 'ORIG_HEAD',
 'packed-refs',
 'refs']

In [36]:
# Diretório que estou trababalhando
os.getcwd()

'c:\\Users\\Win10\\Documents\\airpolution\\scripts'

In [37]:
# Mudo de diretório para o caminho 
os.chdir('C:\\Users\\Win10\\Documents\\')

In [38]:
os.getcwd()

'C:\\Users\\Win10\\Documents'

In [39]:
# Criando diretório
new_path = os.getcwd()+'/test'

if os.path.isdir(new_path):
    print('diretório já existe')
else:
    print('Criando diretório '+new_path)
    os.mkdir(new_path)

diretório já existe


In [40]:
# Criando diretório
new_path = os.getcwd()+'/test2'

if os.path.isdir(new_path):
    print('diretório já existe')
    # Criando um arquivo de texto
    with open(new_path+"/copy.txt", "w") as file:
        file.write("Your text goes here")
else:
    print('Criando diretório '+new_path)
    os.mkdir(new_path)
    with open(new_path+"/copy.txt", "w") as file:
        file.write("Your text goes here")

diretório já existe


## Numpy arrays e Pandas DataFrames

In [41]:
import numpy as np
# Criando uma variável numpy
n = np.array(0)
type(n)

numpy.ndarray

In [42]:
# Criando uma variável numpy a partir de uma lista
myThirdList=[5,10,15,20,25,30]
n = np.array(myThirdList)
print(n)

[ 5 10 15 20 25 30]


In [43]:
# Criando uma matriz de 10x10 de números aleatórios entre 0 e 1
n = np.random.rand(5,5)
print(n)
# Dimensões da matrix
print(n.shape)

[[0.86060784 0.8442683  0.24512778 0.28790354 0.21901993]
 [0.8997877  0.63155015 0.56929188 0.02978985 0.4762774 ]
 [0.80787208 0.17089382 0.88786029 0.45441203 0.8593781 ]
 [0.45599245 0.04665855 0.58820194 0.14712259 0.74830524]
 [0.45759535 0.15678641 0.93437475 0.13556053 0.03095319]]
(5, 5)


In [44]:
# Acessando valores da matriz
n[3,:]

array([0.45599245, 0.04665855, 0.58820194, 0.14712259, 0.74830524])

In [45]:
n[:,3]

array([0.28790354, 0.02978985, 0.45441203, 0.14712259, 0.13556053])

In [46]:
n[:,3:4]

array([[0.28790354],
       [0.02978985],
       [0.45441203],
       [0.14712259],
       [0.13556053]])

In [47]:
n[0,3:4]

array([0.28790354])

In [48]:
n[0,-4]

0.8442682976287262

In [49]:
n[0,3:-1]

array([0.28790354])

In [50]:
n[0,2:]

array([0.24512778, 0.28790354, 0.21901993])

In [51]:
#resultado da matriz de log10
an = np.log(n*10)
print(an)

[[ 2.15246874  2.13330015  0.89660942  1.05745532  0.78399255]
 [ 2.19698867  1.84300717  1.73922309 -1.21100232  1.56083028]
 [ 2.08923354  0.53587223  2.18364421  1.51383415  2.1510388 ]
 [ 1.51730607 -0.76231403  1.77190013  0.386096    2.01264078]
 [ 1.5208151   0.44971428  2.2347074   0.30424806 -1.17269407]]
